#!/usr/bin/env bash
#Creating a script that uses an until loop
i=1
until [ $i -gt 10 ]
do
    echo "Best School"
    ((i++))
done

#!/usr/bin/env bash
#Creating a script that uses an until loop
x=0
until [ $x -gt 9 ]
do
	echo "Holberton School"
	((x++))
done