#!/usr/bin/env bash
# This script displays the content of the current directory in list format
# Only displays the part of the name after the first dash
for i in *
do
    echo "$i" | cut -f 2- -d '-'
done